# Generated by Django 5.0.4 on 2024-04-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='TrueAsnwer',
            field=models.CharField(default='', max_length=200, verbose_name='True Asnwer'),
            preserve_default=False,
        ),
    ]
