# Generated by Django 5.0.4 on 2024-05-12 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_fullexams_exam_exit_and_more'),
        ('users', '0003_alter_result_fullexamreqsult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswerfull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctasnwer', models.CharField(max_length=150, verbose_name='Correct Answer')),
                ('youranser', models.CharField(max_length=150, verbose_name='Your Answer')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examquestionfull')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fullexams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswerquick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctasnwer', models.CharField(max_length=150, verbose_name='Correct Answer')),
                ('youranser', models.CharField(max_length=150, verbose_name='Your Answer')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examquestion')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quickexams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profiles')),
            ],
        ),
    ]
